library(CausalImpact)
set.seed(1)
OnlineDrops<-scan("dropsonlinealpha.csv")
data.frame(OnlineDrops)
Onlinedropstimeseries<-ts(OnlineDrops,frequency=4, start=c(2013, 3))
Onlinedropstimeseries
plot(Onlinedropstimeseries, col=("red"), main="End of Term Online Drops", ylab="drops at online", xlab="Jan 2013-July 2014, adjusted for population", xaxt="n")
points(Onlinedropstimeseries, col="blue", pch=21)
axis(1,at=c(2013.5, 2014.0, 2014.5, 2015.0), labels=c("January", "July", "January","July"))
pre.period <- c(1, 5)
post.period <- c(6, 7)
SAPimpact <- CausalImpact(OnlineDrops, pre.period, post.period)
plot(SAPimpact)
summary(SAPimpact)
summary(SAPimpact, "report")
install.packages("scales")
install.packages("bsts")
library(CausalImpact)
set.seed(1)
#groundDrops<-scan("grounddropsalpha.csv")
groundDrops<-c(932,989,1067,833,886,1023,1088)
grounddropstimeseries<-ts(groundDrops,frequency=4, start=c(2013, 3))
grounddropstimeseries
plot(grounddropstimeseries, col=("red"), main="End of Term Ground Drops", ylab="drops at Ground", xlab="Jan 2013-July 2014, adjusted for population", xaxt="n")
points(grounddropstimeseries, col="blue", pch=21)
axis(1,at=c(2013.5, 2014.0, 2014.5, 2015.0), labels=c("January", "July", "January","July"))
pre.period <- c(1, 5)
post.period <- c(6, 7)
SAPimpactground <- CausalImpact(groundDrops, pre.period, post.period)
plot(SAPimpactground)
summary(SAPimpactground)
summary(SAPimpactground, "report")


